### PR TITLE
Make sidebar more responsive on windows with small heights

### LINKED ISSUE #12: Feedback form overflow
If both the "new Job" and "feedback" forms are opened, the sidebar goes off the bottom of the page & I can't see the submit button. I went through the CSS and can't for the life of me figure out how to fix this.

Screen Shot 2020-11-18 at 8 07 31 AM

### PR DESCRIPTION
**Pull request by imjoshellis**
I changed a few lines in home.styles.scss to make it so the sidebar is visible at all times and take better advantage of flexbox. I'm sure what your build process is, so I only changed the one scss file for now.

- Removed `width` and `margin` from `.job-stuff` and replaced with `flex-grow: 1` which will accomplish the same thing.
- Set `position` of `.side-bar` to `sticky` instead of `fixed` and set `top` to `0` which results in the sidebar scrolling with the main content until it hits the top of the window.
- Set `height` of `.side-bar` to `100vh` instead of `100%` which results in the sidebar having the full window height instead of inheriting height from its parent.  
- Added a little padding to the top and bottom of the sidebar.

To see the new sidebar behavior, it's easiest to make your browser window height artificially small. 

Fixes #12

### CODE REVIEW

**Comment by imjoshellis** [comment]
Note: The internal scrolling behavior on the sidebar is still kinda odd with this setup (each component has separate scrolling). This can be adjusted by adding another div within the sidebar to contain the forms and moving some of the styles around.

In home, for example:

```jsx
<div className='side-bar-wrapper'>
    <div className='side-bar-content'>
        <AddJob />
        <FeedbackForm />
    </div>
</div>
```

I'm happy to add that to the PR as well.

**Comment by elliott-king** [comment]
This gives me a scrollbar on the right side, so I can scroll down when they are open. However, the "new job" section is too short & requires its own scrollbar for a few pixels.

**Comment by imjoshellis** [comment]
@elliott-king That would be fixed by splitting the sidebar into content and wrapper divs. This would give the sidebar a full scroll bar instead of scrolling each component separately as mentioned above. 

I didn't make that change yet b/c I wanted to see what @bbedevian thinks

**Comment by bbedevian** [comment]
Thanks guys, I took a look at it and discussed with Rob. We were thinking from a user experience perspective and how we envisioned the app, it might make the most sense to not allow both menus to be opened at once. First because it kinda clogs up the sidebar and second because it forces this issue of scrolling sidebar which we dont like. The original intent was to only have scroll on the jobs table. What you guys think?

**Comment by imjoshellis** [comment]
I agree the UX would be better if the sidebar swapped between the two menus instead of having both open at once.

**Comment by MisterRK** [comment]
#20 fixes this for now. We are thinking about making the feedback a smaller button with a modal form.

**Pull request closed without merging**
